serviceAccount:
  create: true

sidecar:
  dashboards:
    enabled: true
    provider:
      type: file
      disableDelete: false
      allowUiUpdates: true
    searchNamespace: ALL
securityContext:
  runAsUser: 1001
  fsGroup: 1001
