# Inyectamos el Secret con las credenciales de AWS
extraEnvFrom:
- secretRef:
    name: s3-credentials # Secret con AWS_ACCESS_KEY_ID y AWS_SECRET_ACCESS_KEY

# Configuración del almacenamiento
storage:
  backend: s3
  s3:
    bucket: mimir-metrics1
    endpoint: s3.us-east-1.amazonaws.com
    region: us-east-1
    insecure: false

blocks_storage:
  backend: s3
  s3:
    bucket: mimir-metrics1
    endpoint: s3.us-east-1.amazonaws.com
    region: us-east-1
    insecure: false

# Deshabilitamos persistencia local global ya que usamos S3
persistence:
  enabled: false

# Deshabilitamos MinIO local
minio:
  enabled: false

# Alertmanager: habilitamos persistencia con PVC
alertmanager:
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi # tamaño del PVC

# Ruler: habilitamos persistencia si queremos guardar reglas locales
ruler:
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi

# Componentes que no requieren persistencia
compactor:
  persistence:
    enabled: false

ingester:
  persistence:
    enabled: false

storegateway:
  persistence:
    enabled: false

queryFrontend:
  persistence:
    enabled: false

querier:
  persistence:
    enabled: false

# Recursos
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Réplicas
replicaCount: 1
