# Inyectamos el Secret con las credenciales de AWS
extraEnvFrom:
- secretRef:
    name: s3-credentials # Secret con AWS_ACCESS_KEY_ID y AWS_SECRET_ACCESS_KEY

# Configuración del almacenamiento
storage:
  backend: s3
  s3:
    bucket: mimir-metrics1 # <-- crea este bucket en AWS
    endpoint: s3.us-east-1.amazonaws.com
    region: us-east-1
    insecure: false

# Deshabilitamos persistencia local ya que usamos S3
persistence:
  enabled: false

minio:
  persistence:
    enabled: false

alertmanager:
  persistence:
    enabled: false

compactor:
  persistence:
    enabled: false

ingester:
  persistence:
    enabled: false

storegateway:
  persistence:
    enabled: false

# Recursos
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Réplicas
replicaCount: 1
