loki:
  # Inyectamos el Secret con las credenciales de AWS
  extraEnvFrom:
  - secretRef:
      name: s3-credentials # el Secret que creaste en el namespace de Loki

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks1
      ruler: loki-ruler
    s3:
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
      bucketnames: loki-chunks1
      # Loki tomará AWS_ACCESS_KEY_ID y AWS_SECRET_ACCESS_KEY del Secret
      insecure: false

  schemaConfig:
    configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

  compactor:
    shared_store: s3
