tempo:
  # Inyectamos el Secret con las credenciales de AWS
  extraEnvFrom:
  - secretRef:
      name: s3-credentials

  storage:
    trace:
      backend: s3
      s3:
        bucket: otel-demo-bucket1
        endpoint: s3.amazonaws.com
        region: us-east-1
        # Ya no ponemos access_key ni secret_key hardcodeados
        insecure: false

  compactor:
    backend: s3
