# argo-apps/grafana-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Lorena60/observabilidad.git'
    targetRevision: main
    path: grafana
    helm:
      valueFiles:
      - values.yaml
      - values-grafana.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
