# argo-apps/loki-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Lorena60/observabilidad.git'
    targetRevision: main
    path: loki-stack
    helm:
      valueFiles:
      - values.yaml
      - values-loki.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
