# argo-apps/tempo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Lorena60/observabilidad.git'
    targetRevision: main
    path: tempo
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
